# Generated by Django 4.1.5 on 2023-02-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddModel',
            new_name='EmployeeModel',
        ),
    ]
